### ISSUE TITLE
InitializeOnErrorTargets throws exception

### ISSUE THREAD

**Issue by NorikaDE** [NorikaDE/MsBuild-Parser#1]
Unable to cast object of type 'System.Xml.XmlComment' to type 'System.Xml.XmlElement'.

```
   at Norika.MsBuild.Core.Data.Types.MsBuildXmlNode.GetChildren[T]()
   at Norika.MsBuild.Core.Data.Nodes.MsBuildXmlTargetImplementation.InitializeOnErrorTargets()
   at Norika.MsBuild.Core.Data.Nodes.MsBuildXmlTargetImplementation..ctor(XmlElement targetNode)
   at Norika.MsBuild.Core.Data.MsBuildElementFactory.Create[T](XmlElement element)
   at Norika.MsBuild.Core.Data.Nodes.MsBuildXmlProjectImplementation.InitializeContent[T](MsBuildElementFactory factory)
   at Norika.MsBuild.Core.Data.Nodes.MsBuildXmlProjectImplementation..ctor(XmlDocument document)
   at Norika.MsBuild.Core.Data.MsBuildProjectFile.LoadContent(String content)
   at Norika.MsBuild.DocumentationGenerator.Business.Generator`1.CreateDocumentation(String outputPath)
```

https://github.com/NorikaDE/MsBuild-Parser/blob/f36a1b791ff0c1e93c8774e7ee0d5475ee91be68/Source/Norika.MsBuild.Core.Data/Nodes/MsBuildXmlTargetImplementation.cs#L35-L46

**Comment by NorikaDE** [comment]
This line is not type save

https://github.com/NorikaDE/MsBuild-Parser/blob/f36a1b791ff0c1e93c8774e7ee0d5475ee91be68/Source/Norika.MsBuild.Core.Data/Types/MsBuildXmlNode.cs#L22
